### ISSUE TITLE
Eliminate Goto/Break/Continues from intermediate representation:

### ISSUE THREAD

**Issue by jordwalke** [jordwalke/rehp#5]
Not all languages support these in the same way, and so the Rehp IR(Intermediate Representation) using break/continue makes it hard to add arbitrary backends. This is the primary remaining construct in the IR that is difficult to make work in other languages. Let's change the bytecode compiler to not use these, then remove them from the IR.

**Comment by jordwalke** [comment]
Rehp's IR also has `Break` statements, as well as labeled `Break lbl` statements. In practice, the compiler only outputs non labeled Break statements and those do not cause any challenges.

But the compiler _does_ generate labeled continue statements which are a problem because php/Hack doesn't have any such construct. We previously compiled them to gotos with labels, but Hack is now giving us hard errors for those so we need another approach.

[Here's](https://github.com/jordwalke/rehp/blob/master/compiler/lib/generate.ml#L1695) is the part in `generate.ml` that is responsible for generating labeled continue statements.

It might be possible to change `generate.ml` so that it doesn't even produce labeled continues - that would be ideal, but if it's not possible, below is @robz's proposals on compiling `Continue label` into PHP/Hack that doesn't use Gotos:

-------------------------------------------------------------------------

Hack issues hard warnings on labeled gotos so our approach of compiling Rehp's intermediate representation of `Continue_statement label` into goto statements won't work.


## Implementation for labeled breaks/continues

From-JS and from-bytecode compilation makes use of labeled breaks and continue statements, so we need a way to implement them in Hack.

Code in JS:

```javascript
loop1: for(;;) {
  for(;;) {
    break loop1;
    f();
  }
  f();
}
f();
```

Equivalent code in PHP:

```php
for(;;) {
  for(;;) {
    break 2;
    f();
  }
  f();
}
f();
```

But since "break 2;" is not allowed in our version of Hack (same for goto), we need an alternative way to implement this.


### Alternative 1 - exceptions

```php
class RehackBreakException1 extends Exception { }

try {
  for(;;) {
    for(;;) {
      throw new RehackBreakException1();
      f();
    }
    f();
  }
} catch(RehackBreakException1 $_) {}
f();
```

* Probably not how a human would write this code
* Needs a different exception class for each label, in order to handle nested labels
* Requires wrapping/indenting code within a try
* Looks relatively clean; scales cleanly with deeply nested loops
* Exceptions may be expensive

### ALternative 2 - loop variables

```
$break_loop1 = false;
for(;;) {
  for(;;) {
    $break_loop1 = true;
    break;
    f();
  }
  if ($break_loop1) {
    break;
  }
  f();
}
f();
```

* More like how a human would write this code
* Needs a new flag for every nested labeled loop (see example 2 below)
* Needs a check after every nested loop under a labeled loop
* Harder to implement for deeply nested loops than exceptions
* A lot uglier than exceptions
* But potentially more performant?

## Diabolical Example 1 - Deep nest

JS

```javascript
loop1: 
for(;;) {
  for(;;) {
    for(;;) {
      for(;;) {
        break loop1;
        f();
      }
      f();
    }
    f();
  }
  f();
}
f();
```

PHP

```php
for(;;) {
  for(;;) {
    for(;;) {
      for(;;) {
        break 4;
        f();
      }
      f();
    }
    f();
  }
  f();
}
f();
```

### Alternative 1

```php
class RehackBreakException1 extends Exception { }

try {
  for(;;) {
    for(;;) {
      for(;;) {
        for(;;) {
          throw new RehackBreakException1();
          f();
        }
        f();
      }
      f();
    }
    f();
  }
} catch(RehackBreakException1 $_) {}
f();
```

### Alternative 2

```php
$break_loop1 = false;
for(;;) {
  for(;;) {
    for(;;) {
      for(;;) {
        $break_loop1 = true;
        break;
        f();
      }
      if ($break_loop1) {
        break;
      }
      f();
    }
    if ($break_loop1) {
      break;
    }
    f();
  }
  if ($break_loop1) {
    break;
  }
  f();
}
f();
```

## Diabolical Example 2 - Nested labels

JS

```javascript
loop1: 
for(;;) {
  loop2: 
  for(;;) {
    for(;;) {
      break loop2;
      f();
    }
    break loop1;
    f();
  }
  f();
}
f();
```

PHP

```php
for(;;) {
  for(;;) {
    for(;;) {
      break 2;
      f();
    }
    break 2;
    f();
  }
  f();
}
f();
```

### Alternative 1

```php
class RehackBreakException1 extends Exception {}
class RehackBreakException2 extends Exception {}

try {
  for(;;) {
    try {
      for(;;) {
        for(;;) {
          throw new RehackBreakException1();
          f();
        }
        throw new RehackBreakException2();
        f();
      }
    } catch(RehackBreakException1 $_) {};
    f();
  }
} catch(RehackBreakException2 $_) {};
f();
```

### Alternative 2

```php
$break_loop1 = false;
for(;;) {
  $break_loop2 = false;
  for(;;) {
    for(;;) {
      $break_loop1 = true;
      $break_loop2 = true;
      break;
      f();
    }
    if ($break_loop2) {
      break;
    }
    $break_loop1 = true;
    break;
    f();
  }
  if ($break_loop1) {
    break;
  }
  f();
}
f();
```

**Comment by jordwalke** [comment]
One thing to note is that PHP treats switches as loop constructs that can be continued to - I believe JS doesn't. That's not necessarily relevant here, since I don't think the compiler generate.ml actually outputs any switch statements. If we remove all continues/breaks in PHP output then it won't matter, but just something to be aware of.

Edit: We actually do generate switch statements in the compiler! That means that using any kind of continue/break in the actual PHP output will need to be revisited.

The idea of having a Rehp variant for "continue/break" sounds good in theory because most languages have some kind of utility like this that sound so similar, but in practice I think they differ enough to eliminate them from the rehp intermediate representation.

**Comment by jordwalke** [comment]
I think I like your "Alternative 2 - loop variables" if it does actually work for labeled continues.
I think you could simplify it by having a single variable counter `$n` that keeps track of the remaining levels to continue, and each time decrement it. Not sure if that would work with continues, but it would work with breaks. (Continues are actually the more important one).

Edit: Actually anything that uses a depth counter will have a harder time working in PHP since switches attribute to `n` depth, but they don't in other languages.

**Comment by vouillon** [comment]
I believe we already have most of the machinery to implement a variant of alternative 2. See function `colapse_frontier` in `generate.ml`. The strategy would be to set a variable before exiting the loop by a break, and implement the proper behavior by inserting a conditional statement right after the loop. For instance, instead of this:
```javascript
a:
for (;;) {
  for (;;) {
    if (f()) continue a;
    if (g()) continue;
    break
  }
  h();
}
```
one would generate the following code:
```javascript
a:
for (;;) {
  for (;;) {
    if (f()) {n = 1; break}
    if (g()) continue;
    n = 0; break;
  }
  if (n) continue;
  h();
}
```
Also, quite often, it seems a labelled continue could be avoided by moving part of the code outside of the loop. So, it might be possible to improve `generate.ml` so that it does not produce them as often.

**Comment by jordwalke** [comment]
@vouillon The other question I have is: Is it guaranteed that `Switch_statement`s will not be created inside of these labeled `for(;;)` loops? That is critical for getting `continue`s to work correctly in PHP since PHP treats `switch` as a continuable block, and JS doesn't.

**Comment by vouillon** [comment]
@jordwalke There is no such guarantee. A `continue` within a `switch` statement will be produced for this piece of code:
```ocaml
let rec f n =
  match n with
  | 0 -> 0
  | 1 -> 1
  | 2 -> f (n - 1)
  | _ -> 3
```

**Comment by vouillon** [comment]
It should be possible to use conditionals instead of a `switch` when one of the branchs contains a `continue`.

**Comment by jordwalke** [comment]
Is there any reason why conditionals could not always be used instead of switches?

**Comment by vouillon** [comment]
Switches are potentially faster.

**Comment by robz** [comment]
@vouillon I've been trying to address this, but I've had a hard time following the code in generate.ml. Would you be able to give some pointers for understanding what's being done there? For example, what does the frontier contain?

**Comment by vouillon** [comment]
The code in generate.ml is tricky, indeed...
The frontier is the [dominance frontier](https://en.wikipedia.org/wiki/Dominator_(graph_theory)).
These are the intermediate code blocks that are reachable from the current block, but also from other blocks that are not reachable from the current block. Thus, a JavaScript block will contain the current block and all the blocks reachable from the current block without crossing the dominance frontier.
For instance, if you generate an `if` statement (`if (e) { s1 } else { s2 }; s3`), when generating `s1`, the blocks in the frontier will not be compiled right away, but will end up in `s3`. Also, if there are several blocks in the frontier, `s3` will be a switch that selects between the different blocks. This is implemented by adding a intermediate block during code generation (function `colapse_frontier`).

**Comment by robz** [comment]
This was ultimately addressed by a version of Alternative 2. Relative pull requests are in https://github.com/jordwalke/rehp/pull/20 and https://github.com/jordwalke/rehp/pull/21
