### ISSUE TITLE
Compiling gives bytecode conflict, using 4.07.1, but it's not listed in opam switch

### ISSUE THREAD

**Issue by olleharstedt** [jordwalke/rehp#7]
Trying to use the transpiler as instructed I got an issue. js_of_ocaml is compiled with 4.07.1, but this version is not listed when doing `opam switch`. What's the issue here? How can I attain OCaml 4.07.1?

**Comment by robz** [comment]
Thanks for trying it out! Just to make sure, are you building by running `esy`?

I believe the version of ocaml used is ~4.6.0 when running `esy`: https://github.com/jordwalke/rehp/blob/master/package.json#L22

**Comment by jordwalke** [comment]
@robz @olleharstedt Is using opam to install, but one of our test cases has a bytecode checked in that was compiled with an older version. We can also just remove that test case.

**Comment by olleharstedt** [comment]
I'm using `opam` for my OCaml version, but `esy` to install your product. After changing the package.json file, I now get this nonsensical error:

```
/home/olle/.esy/3_____________________________________________________________________/i/opam__s__js__of__ocaml_compiler-ca47a086/bin/js_of_ocaml: Error: Bytecode version missmatch.
/home/olle/.esy/3_____________________________________________________________________/i/opam__s__js__of__ocaml_compiler-ca47a086/bin/js_of_ocaml: Error: Your ocaml bytecode and the js_of_ocaml compiler have to be compiled with the same version of ocaml.
/home/olle/.esy/3_____________________________________________________________________/i/opam__s__js__of__ocaml_compiler-ca47a086/bin/js_of_ocaml: Error: The Js_of_ocaml compiler has been compiled with ocaml version 4.06.0.
/home/olle/.esy/3_____________________________________________________________________/i/opam__s__js__of__ocaml_compiler-ca47a086/bin/js_of_ocaml: Error: Its seems that your ocaml bytecode has been compiled with an older version of ocaml.
~/kod/ocaml2php$ ocaml --version
The OCaml toplevel, version 4.06.0
```

**Comment by olleharstedt** [comment]
It works now! But the generated PHP is pretty nonsensical. It's not supposed to be readable, I assume? What are the prerequisites to run the generated PHP code? It would be nice if it was PSR-2 standard instead of minified.

**Comment by olleharstedt** [comment]
I also get

```
Missing primitives:
  ArrayLiteral
  caml_arity_test
```

**Comment by jordwalke** [comment]
@olleharstedt Many of the warnings about missing primitives are not accurate.
